source 'https://rubygems.org'

gem 'spree', github: 'spree/spree', branch: '3-0-stable'
gem 'spree_image_cropper', github: 'pero-ict-solutions/spree_image_cropper'
gem 'spree_auth_devise', :git => "git://github.com/spree/spree_auth_devise", :branch => "3-0-stable"

gemspec
